### ISSUE TITLE
[MM] NestedObject flatten

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.cli#47]
If a NestedObject only contains one field, the reviewers from terraform would require us to flatten the structure. For example, on behalf of cli, we have an `api.yml` saying
``` yaml
      - !ruby/object:Api::Type::NestedObject
        name: 'identity'
        description: ''
        required: false
        azure_sdk_references: ['/identity']
        properties:
          - !ruby/object:Api::Type::Enum
            name: 'type'
            description: 'The type of Managed Identity used by the DiskEncryptionSet. Only SystemAssigned is supported.'
            required: false
            azure_sdk_references: ['/identity/type']
            values:
              - :SystemAssigned
            default_value: :SystemAssigned
```
This should be replaced by
``` yaml
      - !ruby/object:Api::Type::Enum
        name: 'identityType'
        description: 'The type of Managed Identity used by the DiskEncryptionSet. Only SystemAssigned is supported.'
        required: false
        azure_sdk_references: ['/identity/type']
        values:
          - :SystemAssigned
        default_value: :SystemAssigned
```
This issue was initially filed to MM [here](https://github.com/VSChina/magic-modules/issues/37)
