### ISSUE TITLE
[MM] Missing properties in `azure_sdk_references`

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.cli#49]
I am generating `api.yaml` file using `autorest.cli` with input file: `azure-rest-api-specs\specification\compute\resource-manager\readme.md`

# Tag in use
`package-2019-07`.

# Cli section added in `readme.md`

``` yaml $(cli)
cli:
  cli-name: compute
  azure-arm: true
  license-header: MICROSOFT_MIT_NO_VERSION
  payload-flattening-threshold: 2
  namespace: azure.mgmt.compute
  package-name: azure-mgmt-compute
  clear-output-folder: false
  debug: true
  disable-azure-cli: true
```

# Problem encountered

In the generated `magic-module-input` files `computediskencryptionset`, we have two sdk_reference 
 `/properties/previousKeys/sourceVault` and `/properties/previousKeys/sourceVault/id` missing.
