### ISSUE TITLE
[MM] Missing fields in `properties` section

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.cli#51]
I am generating `api.yaml` file using `autorest.cli` with input file: `azure-rest-api-specs\specification\compute\resource-manager\readme.md`

# Tag in use
`package-2019-07`.

# Cli section added in `readme.md`

``` yaml $(cli)
cli:
  cli-name: compute
  azure-arm: true
  license-header: MICROSOFT_MIT_NO_VERSION
  payload-flattening-threshold: 2
  namespace: azure.mgmt.compute
  package-name: azure-mgmt-compute
  clear-output-folder: false
  debug: true
  disable-azure-cli: true
```

# Problem encountered

In the generated `magic-module-input` files `computedisk.yaml`, we have some field missing in the `properties` section. To be specific, for struct `KeyVaultAndSecretReference` ([here](https://github.com/Azure/azure-sdk-for-go/blob/0acfc1d1083d148a606d380143176e218d437728/services/compute/mgmt/2019-07-01/compute/models.go#L6303)), one of the field `SourceVault` is not included in `properties` section, thus those fields will not show in the terraform schema.
