### ISSUE TITLE
[MM] `[unknown-primary[object]]` appears in `properties`

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.cli#53]
I am generating `api.yaml` file using `autorest.cli` with input file: `azure-rest-api-specs\specification\compute\resource-manager\readme.md`

# Tag in use
`package-2019-07`.

# Cli section added in `readme.md`

``` yaml $(cli)
cli:
  cli-name: compute
  azure-arm: true
  license-header: MICROSOFT_MIT_NO_VERSION
  payload-flattening-threshold: 2
  namespace: azure.mgmt.compute
  package-name: azure-mgmt-compute
  clear-output-folder: false
  debug: true
  disable-azure-cli: true
```

# Problem encountered

In the generated `magic-module-input` files `computevirtualmachine`, some properties are generated as:
```
            - !ruby/object:Api::Azure::Type::[unknown-primary[object]]
              name: 'settings'
              description: 'Json formatted public settings for the extension.'
              required: false
              azure_sdk_references: ['/resources/settings', '/resources/properties/settings']
            - !ruby/object:Api::Azure::Type::[unknown-primary[object]]
              name: 'protectedSettings'
              description: 'The extension can contain either protectedSettings or protectedSettingsFromKeyVault or no protected settings at all.'
              required: false
              azure_sdk_references: ['/resources/protectedSettings', '/resources/properties/protectedSettings']
```
