### ISSUE TITLE
[MM] duplicated entries in definitions

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.cli#58]
I am generating `api.yaml` file using `autorest.cli` with input file: `azure-rest-api-specs\specification\compute\resource-manager\readme.md`

# Tag in use
`package-2019-07`.

# Cli section added in `readme.md`

``` yaml $(cli)
cli:
  cli-name: compute
  azure-arm: true
  license-header: MICROSOFT_MIT_NO_VERSION
  payload-flattening-threshold: 2
  namespace: azure.mgmt.compute
  package-name: azure-mgmt-compute
  clear-output-folder: false
  debug: true
  disable-azure-cli: true
```

# Problem encountered

The generated `computevirtualmachine/api.yaml` contains two entries with same name `list_by_subscription`:
```
      list_by_subscription: !ruby/object:Api::Azure::SDKOperationDefinition
        go_func_name: ListAll
        python_func_name: list_all
        request:
      list_by_subscription: !ruby/object:Api::Azure::SDKOperationDefinition
        go_func_name: ListByLocation
        python_func_name: list_by_location
        request:
          '/location': !ruby/object:Api::Azure::SDKTypeDefinition::StringObject
            go_field_name: Location
            python_field_name: location
```
