### ISSUE TITLE
[MM] Empty properties for NestedObject

### ISSUE THREAD

**Issue by houkms** [Azure/autorest.cli#69]
actiongroup | package-2019-06-01-only

```yaml
- !ruby/object:Api::Type::Array
        name: 'smsReceivers'
        description: 'The list of SMS receivers that are part of this action group.'
        output: true
        azure_sdk_references: ['/smsReceivers', '/properties/smsReceivers']
        item_type: !ruby/object:Api::Type::NestedObject
          properties:
      - !ruby/object:Api::Type::Array
        name: 'webhookReceivers'
        description: 'The list of webhook receivers that are part of this action group.'
        output: true
        azure_sdk_references: ['/webhookReceivers', '/properties/webhookReceivers']
        item_type: !ruby/object:Api::Type::NestedObject
          properties:
```
