### ISSUE TITLE
[MM] Missing properties

### ISSUE THREAD

**Issue by houkms** [Azure/autorest.cli#70]
addonsoperation | package-2017-05

```yaml
--- !ruby/object:Api::Product
name: Azure Operation Management
versions:
  - !ruby/object:Api::Product::Version
    name: ga
    base_url: NotUsedInAzure
scopes:
  - NotUsedInAzure
objects:
  - !ruby/object:Api::Resource
    name: Operation
    api_name: Addons
    base_url: NotUsedInAzure

    azure_sdk_definition: !ruby/object:Api::Azure::SDKDefinition
      provider_name: Microsoft.Addons
      go_client_namespace: addons
      go_client: operationsClient
      python_client_namespace: azure.mgmt.addons
      python_client: AzureAddonsResourceProviderClient.operations
      list_by_subscription: !ruby/object:Api::Azure::SDKOperationDefinition
        go_func_name: List
        python_func_name: list
        request:

    description: |
      Manage Azure Operation instance.
    properties:
      # read only values included only in response
```
