### ISSUE TITLE
[MM] No properties body specified for resource.

### ISSUE THREAD

**Issue by houkms** [Azure/autorest.cli#71]
addonssupportplantype | package-2017-05

```yaml
description: |
      Manage Azure SupportPlanType instance.
    properties:
      - !ruby/object:Api::Type::String
        name: 'providerName'
        description: 'The support plan type. For now the only valid type is "canonical".'
        required: true
        input: true
        azure_sdk_references: ['providerName']
      - !ruby/object:Api::Type::String
        name: 'name'
        description: 'The Canonical support plan type.'
        required: true
        input: true
        azure_sdk_references: ['planTypeName']
      # read only values included only in response
      - !ruby/object:Api::Type::String
        name: 'id'
        description: 'The id of the ARM resource, e.g. "/subscriptions/{id}/providers/Microsoft.Addons/supportProvider/{supportProviderName}/supportPlanTypes/{planTypeName}".'
        output: true
        azure_sdk_references: ['/id']
      - !ruby/object:Api::Type::String
        name: 'name'
        description: 'The name of the Canonical support plan, i.e. "essential", "standard" or "advanced".'
        output: true
        azure_sdk_references: ['/name']
      - !ruby/object:Api::Type::String
        name: 'type'
        description: 'Microsoft.Addons/supportProvider'
        output: true
        azure_sdk_references: ['/type']
      - !ruby/object:Api::Type::Enum
        name: 'provisioningState'
        description: 'The provisioning state of the resource.'
        output: true
        azure_sdk_references: ['/provisioningState', '/properties/provisioningState']
        values:
          - :Succeeded
          - :Failed
          - :Cancelled
          - :Purchasing
          - :Downgrading
          - :Cancelling
          - :Upgrading
```
