### ISSUE TITLE
[MM] Missing go_client_namespace

### ISSUE THREAD

**Issue by houkms** [Azure/autorest.cli#72]
webservice|package-webservices-2017-01

```yaml
 azure_sdk_definition: !ruby/object:Api::Azure::SDKDefinition
      provider_name: Microsoft.MachineLearning
      go_client_namespace: 
      go_client: webServicesClient
      python_client_namespace: 
      python_client: AzureMLWebServicesManagementClient.web_services
```
