### ISSUE TITLE
It doesn't generate api.yml for RP PowerBIDedicated

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/autorest.cli#91]
The autorest command I used is "autorest --cli --use=C:/terraform/projects/autorest.cli --mm --output-folder=C:/terraform/generated --tag=package-2017-10-01 C:\terraform\projects\azure-rest-api-specs\specification\powerbidedicated\resource-manager\readme.md".

RP's path: https://github.com/neil-yechenwei/azure-rest-api-specs/blob/master/specification/powerbidedicated/resource-manager/readme.md

Add below code to above readme.md:
``` yaml $(cli)
cli:
  cli-name: powerbidedicated
  azure-arm: true
  license-header: MICROSOFT_MIT_NO_VERSION
  payload-flattening-threshold: 2
  namespace: azure.mgmt.powerbidedicated
  package-name: azure-mgmt-powerbidedicated
  clear-output-folder: false
  disable-mm: false
  disable-azure-cli: true
```
